In [2]:
import os
import argparse
import numpy as np
from skimage.io import imread, imread_collection, imsave, MultiImage
from scipy.ndimage import uniform_filter
from skimage.filters import gaussian
from datetime import datetime

In [5]:
in_dir = "/home/andre/Heinemann_lab/Code/Flatfield_correction/testing_input/Single_channel_timecourse"
tif_fns = os.listdir(in_dir)
tif_fps = [os.path.join(in_dir, i) for i in tif_fns]

In [10]:
raw_images = MultiImage(tif_fps, conserve_memory=True)
base_im = np.full(
        raw_images[0][0,:,:].shape, 
        500
        )

In [40]:
# ims = (np.subtract(i, base_im) for j in raw_images for i in j)
ims = (np.subtract(i, base_im) for i in raw_images)

In [47]:
test = next(ims)

In [46]:
test.shape

(409, 512, 512)

In [36]:
imsave()

array([[0, 0, 6, ..., 0, 3, 6],
       [1, 4, 0, ..., 1, 0, 2],
       [0, 0, 0, ..., 1, 6, 0],
       ...,
       [1, 2, 0, ..., 2, 0, 6],
       [0, 0, 2, ..., 5, 0, 0],
       [2, 0, 1, ..., 4, 4, 0]], dtype=uint16)

In [6]:
data = np.arange(24).reshape(2, 3, 4)
print(data)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [48]:
test = (i for i in range(10))
for i in range(10):
    print(test)

<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
<generator object <genexpr> at 0x7f831cda14a0>
